general.import = [
    "~/.config/alacritty/alacritty-theme/themes/monokai_pro.toml"
]

[window]
opacity = 0.85
blur = true
padding.y = 10
padding.x = 10

decorations = "Buttonless"

[font]
normal.family = "SF Mono Powerline"
size = 13
